# Generated by Django 4.2 on 2023-05-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_remove_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to='logo'),
        ),
    ]
