# Generated by Django 4.2 on 2023-05-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_company_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_logo',
        ),
    ]
