# Generated by Django 4.2 on 2023-05-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_remove_company_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
